name: Build & Test Outposts

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle with cache
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' && github.event_name != 'push' }}

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build and Test with Gradle
        run: ./gradlew build -Dorg.gradle.java.home="$JAVA_HOME"

      - name: Upload compiled plugin artifact
        uses: actions/upload-artifact@v4
        with:
          name: Outposts-Release
          path: build/libs/Outposts-*.jar
          if-no-files-found: error

      - name: Publish Latest GitHub Release
        if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "latest"
          target_commitish: ${{ github.sha }}
          name: "Latest Release"
          prerelease: false
          make_latest: "true"
          files: build/libs/Outposts-*.jar
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
